In [6]:
# try catch
try:
    strs = sfds
    a = 5/0
except ZeroDivisionError:
    print("error")
except NameError:
    print("name error")

name error


In [33]:
s=["Americans ","Indians"]
verb=["play","watch"]
o=["Baseball","Cricket"]
lst = [(sub+" "+veb+" "+ob) for sub in s for veb in verb for ob in o]
#print(lst)
for i in lst:
    print(i)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [23]:
#numpy.vander
import numpy as np
x = np.array([1, 2, 3, 4,5])
#print(x)
N = 5
print(np.vander(x, N,False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
